### ISSUE TITLE
Invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by carusyte** [chrislusf/gleam#57]
I have a large data set divided to groups, each group requires heavy calculation and I submit them to gleam flow to do the job (concurrently). For each group of data set I'd called `flow.New()...Run(distributedOption)`, but when the whole process progressed at about 1.5% or so, I got a nil pointer error. Processing the group of data set individually at which the whole process failed didn't trigger the error. Is it safe to call `flow.New()...Run(distributedOption)` concurrently, or is there any limitation in it? Is it advisable to submit groups of data set through channel instead of creating new flow for each?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x458651]

goroutine 103250 [running]:
github.com/golang/protobuf/proto.(*Buffer).EncodeRawBytes(0xc424b23528, 0x0, 0x9c, 0x9c, 0x0, 0x0)
/path/to/go/src/github.com/golang/protobuf/proto/encode.go:201 +0x8f
github.com/golang/protobuf/proto.(*Buffer).enc_proto3_slice_byte(0xc424b23528, 0xc42039fcc0, 0xc4218bdec0, 0xc4200103c0, 0xc420010301)
/path/to/go/src/github.com/golang/protobuf/proto/encode.go:691 +0x130
github.com/golang/protobuf/proto.(*Buffer).enc_struct(0xc424b23528, 0xc420d7f0e0, 0xc4218bdec0, 0x0, 0xc428123460)
/path/to/go/src/github.com/golang/protobuf/proto/encode.go:1235 +0x3c6
github.com/golang/protobuf/proto.(*Buffer).enc_len_struct.func1(0xc420380320, 0xc42155eae0)
/path/to/go/src/github.com/golang/protobuf/proto/encode.go:1305 +0x3c
github.com/golang/protobuf/proto.(*Buffer).enc_len_thing(0xc424b23528, 0xc428123518, 0xc428123628, 0x41223d, 0xc424b23528)
/path/to/go/src/github.com/golang/protobuf/proto/encode.go:1313 +0x7f
github.com/golang/protobuf/proto.(*Buffer).enc_len_struct(0xc424b23528, 0xc420d7f0e0, 0xc4218bdec0, 0xc428123628, 0xc428123638, 0x50f0a9)
/path/to/go/src/github.com/golang/protobuf/proto/encode.go:1305 +0x6d
github.com/golang/protobuf/proto.(*Buffer).enc_slice_struct_message(0xc424b23528, 0xc4203dfa40, 0xc42220aae0, 0x0, 0x0)
/path/to/go/src/github.com/golang/protobuf/proto/encode.go:985 +0x199
github.com/golang/protobuf/proto.(*Buffer).enc_struct(0xc424b23528, 0xc420d7f040, 0xc42220aae0, 0x0, 0x0)
/path/to/go/src/github.com/golang/protobuf/proto/encode.go:1235 +0x3c6
github.com/golang/protobuf/proto.(*Buffer).enc_len_struct.func1(0xc424b23528, 0xa)
/path/to/go/src/github.com/golang/protobuf/proto/encode.go:1305 +0x3c
github.com/golang/protobuf/proto.(*Buffer).enc_len_thing(0xc424b23528, 0xc428123840, 0xc428123950, 0x41223d, 0xc424b23528)
/path/to/go/src/github.com/golang/protobuf/proto/encode.go:1313 +0x7f
github.com/golang/protobuf/proto.(*Buffer).enc_len_struct(0xc424b23528, 0xc420d7f040, 0xc42220aae0, 0xc428123950, 0x0, 0x0)
/path/to/go/src/github.com/golang/protobuf/proto/encode.go:1305 +0x6d
github.com/golang/protobuf/proto.(*Buffer).enc_slice_struct_message(0xc424b23528, 0xc4203df400, 0xc423ca5720, 0x0, 0x0)
/path/to/go/src/github.com/golang/protobuf/proto/encode.go:985 +0x199
github.com/golang/protobuf/proto.(*Buffer).enc_struct(0xc424b23528, 0xc420d7ef00, 0xc423ca5720, 0xdfb7c0, 0xc423ca5720)
/path/to/go/src/github.com/golang/protobuf/proto/encode.go:1235 +0x3c6
github.com/golang/protobuf/proto.(*Buffer).Marshal(0xc424b23528, 0x12d4c60, 0xc423ca5720, 0xc428231900, 0x0)
/path/to/go/src/github.com/golang/protobuf/proto/encode.go:274 +0x2b4
google.golang.org/grpc.protoCodec.marshal(0xdfb7c0, 0xc423ca5720, 0xc424b23520, 0xc421f49a54, 0xc42588c1f8, 0xc422b28c50, 0xb, 0xc42588c150)
/path/to/go/src/google.golang.org/grpc/codec.go:63 +0xe8
google.golang.org/grpc.protoCodec.Marshal(0xdfb7c0, 0xc423ca5720, 0xc422f38ec8, 0xc423848340, 0x9b, 0xc422b28c88, 0x411230)
/path/to/go/src/google.golang.org/grpc/codec.go:73 +0x73
google.golang.org/grpc.(*protoCodec).Marshal(0x133f108, 0xdfb7c0, 0xc423ca5720, 0x1320a00, 0xe786a8, 0xc423848358, 0xc422b28c70, 0x41223d)
<autogenerated>:48 +0x59
google.golang.org/grpc.encode(0x12d7e20, 0x133f108, 0xdfb7c0, 0xc423ca5720, 0x0, 0x0, 0x0, 0x0, 0xc422b28f90, 0x2, ...)
/path/to/go/src/google.golang.org/grpc/rpc_util.go:302 +0x2c4
google.golang.org/grpc.(*clientStream).SendMsg(0xc426c0c160, 0xdfb7c0, 0xc423ca5720, 0x0, 0x0)
/path/to/go/src/google.golang.org/grpc/stream.go:365 +0x11d
github.com/chrislusf/gleam/pb.(*gleamMasterSendFlowExecutionStatusClient).Send(0xc421130020, 0xc423ca5720, 0x0, 0x1)
/path/to/go/src/github.com/chrislusf/gleam/pb/gleam.pb.go:1929 +0x49
github.com/chrislusf/gleam/distributed/driver.(*FlowDriver).reportStatus(0xc423cc8000, 0x12d8620, 0xc423cc8ac0, 0xc420373030, 0xe53ca9, 0xf, 0xc4257c6300)
/path/to/go/src/github.com/chrislusf/gleam/distributed/driver/driver.go:154 +0x39d
created by github.com/chrislusf/gleam/distributed/driver.(*FlowDriver).RunFlowContext
/path/to/go/src/github.com/chrislusf/gleam/distributed/driver/driver.go:93 +0x4d8
```

**Comment by chrislusf** [comment]
you mean multiple flows at the same time?

**Comment by carusyte** [comment]
Yes. Is this paradigm supported?

**Comment by chrislusf** [comment]
I have not tried this myself.

**Comment by chrislusf** [comment]
It's better just send all the data, partition it, and let all the executors handle the workload.

**Comment by carusyte** [comment]
Well, if that's so, I'll have to refactor my client code.
What does Partition() actually do? Is it compatible with RoundRobin()? I remember I just skip the Partition() call due to #53 .
