### ISSUE TITLE
BUG: when Step Emit one empty string field the next step will panic [index out of range]

### ISSUE THREAD

**Issue by qazqwe1596357** [chrislusf/gleam#90]
One step Emit Row with one empty string field the next step will panic, the panic is "panic: runtime error: index out of range".

for example, in gleam/examples/word_count_in_go.go 

And then add one empty line in "/etc/passwd", then run the word_count_in_go binary, you will get the panic info below.
I found when Row Emited has empty string field will trigger this problem.

in go code like below will triger this problem
```
vec = []interface{}{"", "b"}
gio.Emit(vec...)
```

the panic info:

```
$ ./word_count_in_go 
panic: runtime error: index out of range

goroutine 21 [running]:
github.com/glycerine/truepack/msgp.(*NilBitsStack).ReadStringBytes(0xc42004cc38, 0xc4201fa5a9, 0x11, 0x11, 0x8, 0x4, 0x0, 0x0, 0xc42004ca68, 0x493a7f, ...)
        gopath/src/github.com/glycerine/truepack/msgp/read_bytes.go:982 +0x167
github.com/glycerine/truepack/msgp.(*NilBitsStack).ReadIntfBytes(0xc42004cc38, 0xc4201fa5a9, 0x11, 0x11, 0x1, 0x1, 0x11, 0x11, 0x0, 0x0, ...)
        gopath/src/github.com/glycerine/truepack/msgp/read_bytes.go:1294 +0x2e6
github.com/chrislusf/gleam/util.(*Row).UnmarshalMsgWithCfg(0xc42022c300, 0xc4201fa5a9, 0x11, 0x11, 0xc42004cd77, 0xc42004cd78, 0x411768, 0x40, 0xb91520, 0x1)
        gopath/src/github.com/chrislusf/gleam/util/row_codec.go:362 +0x2ce
github.com/chrislusf/gleam/util.(*Row).UnmarshalMsg(0xc42022c300, 0xc4201fa5a0, 0x1a, 0x1a, 0x0, 0xc42017ba58, 0x15f86b4ba09, 0xfc5d80, 0xc42009a008)
        gopath/src/github.com/chrislusf/gleam/util/row_codec.go:282 +0x64
github.com/chrislusf/gleam/util.DecodeRow(0xc4201fa5a0, 0x1a, 0x1a, 0x1a, 0x1a, 0x0)
        gopath/src/github.com/chrislusf/gleam/util/row_read_write.go:55 +0x79
github.com/chrislusf/gleam/util.ReadRow(0xfc5d40, 0xc42009a000, 0x1, 0x0, 0x0)
        gopath/src/github.com/chrislusf/gleam/util/row_read_write.go:29 +0x199
github.com/chrislusf/gleam/gio.(*gleamRunner).doProcessMapper(0xc42009a180, 0xfcf880, 0xc42021cb00, 0xc2e990, 0x0, 0x0)
        gopath/src/github.com/chrislusf/gleam/gio/mapper.go:20 +0x4b
github.com/chrislusf/gleam/gio.(*gleamRunner).processMapper.func1(0x0, 0x0)
        gopath/src/github.com/chrislusf/gleam/gio/mapper.go:14 +0x45
github.com/chrislusf/gleam/gio.(*gleamRunner).report.func1(0xc4201d1e60, 0xc42017b330)
        gopath/src/github.com/chrislusf/gleam/gio/reporter.go:23 +0x27
created by github.com/chrislusf/gleam/gio.(*gleamRunner).report
        gopath/src/github.com/chrislusf/gleam/gio/reporter.go:25 +0x1aa
```

**Comment by chrislusf** [comment]
please "go get -u github.com/glycerine/truepack" and confirm the fix.

**Comment by qazqwe1596357** [comment]
fixed
